### ISSUE TITLE
Deep Integration With LibreOffice

### ISSUE THREAD

**Issue by Terahertz0** [peter88213/yw-cnv#2]
Is there a way to modify this extension so that by simply double-clicking the yWriter7 file from the desktop, LibreOffice will import the file correctly, rather than using the internal import option in the file menu?

Also for exporting, Can the Save As menu in LibreOffice contain the .yw7 extension, rather than using the internal file menu?

**Comment by peter88213** [comment]
> Is there a way to modify this extension so that by simply double-clicking the yWriter7 file from the desktop, LibreOffice will import the file correctly, rather than using the internal import option in the file menu?

Yes, the [yW2OO standalone converter](https://peter88213.github.io/yW2OO/) can be launched by the Windows Explorer context menu on .yw7 files. On setup, a registry file is generated that has to be started manually by opening the installation folder and double clicking _add_context_menu.reg_. Then a new context menu entry "Export to OpenOffice" shows up when right-clicking .yw7 files. Note that this requires a Python installation on your PC (see system requirements).

> Also for exporting, Can the Save As menu in LibreOffice contain the .yw7 extension, rather than using the internal file menu?

I think this might be feasible. Among other things, the  yw-cnv extension consists of a Python script and the [AddonUI.xcu configuration file](https://github.com/peter88213/yw-cnv/blob/main/oxt/AddonUI.xcu) which links the Python subroutines to the LibreOffice user interface. If you want a new menu entry, you can edit the _OfficeMenuBarMerging_ section.

**Comment by peter88213** [comment]
Further investigation reveals that one would need to implement the Export-to-yw7 feature as a _filter_ to make it callable from the "Save as" menu. It looks like filters are Java classes implementing a standardized interface. As appealing as this task would be, it would come down to a completely different programming approach. 

See: 
https://wiki.openoffice.org/wiki/Documentation/DevGuide/OfficeDev/Filter

**Comment by peter88213** [comment]
> Is there a way to modify this extension so that by simply double-clicking the yWriter7 file from the desktop, LibreOffice will import the file correctly, rather than using the internal import option in the file menu?

> Yes, the [yW2OO standalone converter](https://peter88213.github.io/yW2OO/) can be launched by the Windows Explorer context menu on .yw7 files. On setup, a registry file is generated that has to be started manually by opening the installation folder and double clicking _add_context_menu.reg_. Then a new context menu entry "Export to OpenOffice" shows up when right-clicking .yw7 files. Note that this requires a Python installation on your PC (see system requirements).

As of version 5, [yW2OO](https://peter88213.github.io/yW2OO/) can also convert ODT/ODS documents to *.yw7*.
