### ISSUE TITLE
export outline in proof version

### ISSUE THREAD

**Issue by morgan-53** [peter88213/yw-cnv#3]
I export to using proof reading to write in LO instead of YW. Is there a way to have "outline" scenes show up in the proof version? Whenever I export, they don't show up, so I change them to "draft" and export again. The "outline" designation helps me keep up with stuff in YW.

**Comment by peter88213** [comment]
Are you sure you mean scenes with the "outline" completion status? These should be imported and exported; in general, the status has no effect on the conversion. 

Another thing is the scene type. Scenes marked "unused" are no longer imported to the "_proof" document as of version 1.33.0. So if you want to include "unused", "notes" and "todo" scenes in your "_proof" document, you may want to go back and try version 1.32.7:

[Download yw-cnv-L-1.32.7.oxt](/https://github.com/peter88213/yw-cnv/releases/download/v1.32.7/yw-cnv-L-1.32.7.oxt)

**Comment by peter88213** [comment]
I made sure that v1.35.3 imports scenes with "outline" status properly from .yw7 to the "_proof" document. 

See the  yw7 test project and the imported document in the attached zipfile: 
[yw7-test.zip](https://github.com/peter88213/yw-cnv/files/12053338/yw7-test.zip)

The test project was created with yWriter version 7.1.3.6 Beta.
